name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, Thanks for opening your first Issue. I will review it soon, Thanks"
        pr-message: "Hello, Thanks for opening your first Pull request. I will review it soon, Thanks"
