FROM centos:7
#if it takes time to build docker image or it got stuck while building, then use "amazonlinux:latest" as the base image
# Install necessary packages
RUN yum update -y
RUN yum install -y git wget openssh-server
#shadow-utils will provide us the "chpasswd" command, which we will use to change root password
RUN yum install -y shadow-utils-2:4.9-12.amzn2023.0.2.x86_64
RUN yum install python3 -y
# Download and install Oracle JDK
RUN wget https://download.oracle.com/java/17/archive/jdk-17.0.8_linux-x64_bin.rpm
RUN yum install -y jdk-17.0.8_linux-x64_bin.rpm

# Set root password
RUN echo 'root:redhat' | chpasswd

# Configure SSH
RUN ssh-keygen -A

# Define the default command to run when the container starts
CMD ["/usr/sbin/sshd", "-D"]