- hosts: localhost
  vars_files:
    - aws_credential.yml
    - instance_vars.yml
  tasks:
    - package:
        name: haproxy 
        state: present
    - amazon.aws.ec2_instance_info:
        aws_access_key: "{{ aws_access_key  }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "Ansible-ec2-instance-target-node"
          instance-state-name: ["running"]
      register: ec2

    - set_fact:
        private_ip: "{{ ec2.instances | map(attribute='private_ip_address') | list  }}"

    - debug:
        var: private_ip

    - template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg

    - service:
        name: haproxy
        state: restarted